version: '3'

services:

    api:
        build:
            context: ./services/api
            args:
                NODE_ENV: development
        command: npm run dev
        environment:
            NODE_ENV: development
            AMQP_URI: amqp://rabbitmq
        volumes:
            - ./services/api/src:/app/src
        restart: always
        depends_on:
            - rabbitmq

    container:
        build:
            context: ./services/container
            args:
                NODE_ENV: development
        command: npm run dev
        environment:
            NODE_ENV: development
            AMQP_URI: amqp://rabbitmq
        volumes:
            - ./services/container/src:/app/src
        restart: always
        depends_on:
            - rabbitmq
    
    rabbitmq:
        image: rabbitmq:3.7-alpine
        hostname: rabbitmq
        volumes:
            - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq
        restart: always
        healthcheck:
            test: [ "CMD", "nc", "-z", "localhost", "5672" ]
            interval: 5s
            timeout: 15s
            retries: 5