version: '3.5'

networks:

    proxy:
        name: proxy
        driver: overlay
    apps:
        name: apps
        driver: overlay
    micros:
        name: micros
        driver: overlay
    db:
        name: db
        driver: overlay

services:

    api:
        build:
            context: ./services/api
            args:
                NODE_ENV: development
        image: optimusdeploy_api:dev
        ports:
            - 3000:3000
        command: npm run dev
        environment:
            NODE_ENV: development
            AMQP_URI: amqp://rabbitmq
            API_PORT: 3000
            ELASTIC_APM_SERVICE_NAME: optimus-deploy-api
            ELASTIC_APM_SERVER_URL: http://apm-server:8200
        volumes:
            - ./services/api/src:/app/src
        networks:
            - micros
            - proxy
        deploy:
            labels:
                - "traefik.docker.network=proxy"
                - "traefik.backend=api"
                - "traefik.frontend.rule=Host:api.local"
                - "traefik.port=3000"
                - "traefik.enable=true"

    orchestrator:
        build:
            context: ./services/orchestrator
            args:
                NODE_ENV: development
        image: optimusdeploy_orchestrator:dev
        command: npm run dev
        environment:
            NODE_ENV: development
            AMQP_URI: amqp://rabbitmq
        volumes:
            - ./services/orchestrator/src:/app/src
        networks:
            - micros

    user:
        build:
            context: ./services/user
            args:
                NODE_ENV: development
        image: optimusdeploy_user:dev
        command: npm run dev
        environment:
            NODE_ENV: development
            AMQP_URI: amqp://rabbitmq
            MONGODB_HOST: mongodb://mongodb
            GITHUB_CLIENT_ID: 129800c9747092aabe46
            GITHUB_CLIENT_SECRET: 267225d33106584503b84551d493e77bbdd7b0b8
            GOOGLE_CLIENT_ID: 666163516742-b89cg46pnk6o8p75b9btgp7o03gvv081.apps.googleusercontent.com
            GOOGLE_CLIENT_SECRET: OzxCxTGs8PJedpi4y1VeqdRH
        volumes:
            - ./services/user/src:/app/src
        networks:
            - micros
            - db

    container:
        build:
            context: ./services/container
            args:
                NODE_ENV: development
        image: optimusdeploy_container:dev
        command: npm run dev
        environment:
            NODE_ENV: development
            AMQP_URI: amqp://rabbitmq
            MONGODB_HOST: mongodb://mongodb
            DATA_DIR: /srv/daemon-data
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./services/container/src:/app/src
            - /srv/daemon-data:/srv/daemon-data
        networks:
            - micros
            - db
            
    mailer:
        build:
            context: ./services/mailer
            args:
                NODE_ENV: development
        image: optimusdeploy_mailer:dev
        command: npm run dev
        environment:
            NODE_ENV: development
            AMQP_URI: amqp://rabbitmq
            SENDGRID_API_KEY: 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
        volumes:
            - ./services/mailer/src:/app/src
        networks:
            - micros

    mongodb:
        image: mvertes/alpine-mongo
        ports:
            - 27017:27017
        volumes:
            - /srv/utils/mongodb:/data/db
        networks:
            - db
    
    rabbitmq:
        image: rabbitmq:3-management
        hostname: rabbitmq  #The hostname has to be manually specified. Refer to hub.docker.com/_/rabbitmq
        volumes:
            - /srv/utils/rabbitmq:/var/lib/rabbitmq/
        networks:
            - micros
            - proxy
        deploy:
            labels:
                - "traefik.docker.network=proxy"
                - "traefik.backend=rabbitmq"
                - "traefik.frontend.rule=Host:rabbitmq.local"
                - "traefik.port=15672"
                - "traefik.enable=true"

    traefik:
        image: traefik
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./config/traefik/traefik-dev.compose.toml:/etc/traefik/traefik.toml
            - ./config/traefik/traefik.crt:/etc/traefik/traefik.crt
            - ./config/traefik/traefik.key:/etc/traefik/traefik.key
        networks:
            - proxy
        deploy:
            labels:
                - "traefik.backend=traefik"
                - "traefik.frontend.rule=Host:traefik.local"
                - "traefik.port=8080"
                - "traefik.enable=true"