version: '3.5'

networks:

    proxy:
        name: proxy
    apps:
        name: apps
    micros:
        name: micros
    db:
        name: db

services:

    api:
        image: hariaakash/op-static
        labels:
            - "traefik.docker.network=proxy"
            - "traefik.backend=haxforlyf.local"
            - "traefik.frontend.rule=Host:haxforlyf.local"
            - "traefik.port=80"
            - "traefik.enable=true"
        networks:
            - apps
            - proxy

    orchestrator:
        build: ./services/orchestrator
        command: npm run start
        environment:
            NODE_ENV: production
            AMQP_URI: amqp://rabbitmq
        volumes:
            - ./services/orchestrator/src:/app/src
        restart: always
        depends_on:
            - rabbitmq
        networks:
            - micros

    user:
        build: ./services/user
        command: npm run start
        environment:
            NODE_ENV: production
            AMQP_URI: amqp://rabbitmq
            MONGODB_HOST: mongodb://mongodb
        volumes:
            - ./services/user/src:/app/src
        restart: always
        depends_on:
            - rabbitmq
            - mongodb
        networks:
            - micros
            - db

    mongodb:
        image: mvertes/alpine-mongo
        volumes:
            - ./data/mongodb:/data/db
        networks:
            - db

    rabbitmq:
        image: rabbitmq:3.7-alpine
        hostname: rabbitmq
        volumes:
            - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq
        restart: always
        networks:
            - micros

    traefik:
        image: traefik
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./config/traefik/traefik-pro.toml:/etc/traefik/traefik.toml
            - ./data/traefik/acme.json:/acme.json
        restart: always
        networks:
            - proxy