version: '3.5'

networks:

    elastic:
        name: elastic
        driver: overlay
    proxy:
        name: proxy
        driver: overlay
        external: true

services:

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
        # user: root
        # volumes:
        #     - ./logs/elasticsearch/:/usr/share/elasticsearch/logs/
        #     - es_data:/usr/share/elasticsearch/data
        networks:
            - elastic
        healthcheck:
            test: curl -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
            interval: 30s
            timeout: 10s
            retries: 5
        deploy:
            placement:
                constraints: [node.role == manager]

    kibana:
        image: docker.elastic.co/kibana/kibana-oss:6.6.1
        ports:
            - 5601:5601
        networks:
            - elastic
            - proxy
        deploy:
            labels:
                - "traefik.docker.network=proxy"
                - "traefik.backend=kibana"
                - "traefik.frontend.rule=Host:kibana.local"
                - "traefik.port=5601"
                - "traefik.enable=true"
            placement:
                constraints: [node.role == manager]
        healthcheck:
            test: curl -s https://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
            interval: 30s
            timeout: 10s
            retries: 5
        depends_on:
            - elasticsearch

    logstash:
        image: docker.elastic.co/logstash/logstash:6.6.1
        volumes:
            - ./logs/logstash/:/var/log/
            - ./config/logstash/pipelines/:/usr/share/logstash/pipeline/
        networks:
            - elastic
        deploy:
            placement:
                constraints: [node.role == manager]

    metricbeat:
        image: docker.elastic.co/beats/metricbeat-oss:6.6.1
        # container_name: metricbeat
        user: root
        secrets:
            - source: metricbeat.yml
              target: /usr/share/metricbeat/metricbeat.yml
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
            - /proc:/hostfs/proc:ro
            - /:/hostfs:ro
        networks:
            - elastic
        deploy:
            placement:
                constraints: [node.role == manager]    
            restart_policy:
                condition: on-failure
        healthcheck:
            test: metricbeat test config
            interval: 30s
            timeout: 15s
            retries: 5
        depends_on:
            - kibana

    filebeat:
        image: docker.elastic.co/beats/filebeat:6.6.1
        user: root
        secrets:
            - source: filebeat.yml
              target: /usr/share/filebeat/filebeat.yml
        volumes:
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - ./logs/:/var/logs/
        networks:
            - elastic
        deploy:
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
        healthcheck:
            test: filebeat test config
            interval: 30s
            timeout: 15s
            retries: 5
        depends_on:
            - kibana

secrets:

    filebeat.yml:
        file: ./config/filebeat/filebeat.yml

    metricbeat.yml:
        file: ./config/metricbeat/metricbeat.yml