version: '3.5'

networks:

    proxy:
        name: proxy
        driver: overlay
        external: true
    micros:
        name: micros
        driver: overlay
        external: true
    db:
        name: db
        driver: overlay
        external: true

services:

    api:
        image: registry.local/optimusdeploy_api:dev
        command: npm run dev
        environment:
            NODE_ENV: development
            AMQP_URI: amqp://rabbitmq
            API_PORT: 3000
            ELASTIC_APM_SERVICE_NAME: optimus-deploy-API
            ELASTIC_APM_SERVER_URL: http://apm-server:8200
            ELASTIC_APM_HOSTNAME: "express-api"
            ELASTIC_APM_FRAMEWORK_NAME: "Express"
            ELASTIC_APM_FRAMEWORK_VERSION: "~4.16.0"
        networks:
            - micros
            - proxy
        deploy:
            mode: replicated
            replicas: 1
            labels:
                - "traefik.docker.network=proxy"
                - "traefk.docker.domain=api.local"
                - "traefik.backend=api.local"
                - "traefik.frontend.rule=Host:www.api.local,api.local"
                - "traefik.port=3000"
                - "traefik.enable=true"
            placement:
                constraints: [node.role == worker]

    orchestrator:
        image: registry.local/optimusdeploy_orchestrator:dev
        command: npm run dev
        environment:
            NODE_ENV: development
            AMQP_URI: amqp://rabbitmq
            ELASTIC_APM_SERVICE_NAME: optimus-deploy-orchestrator
            ELASTIC_APM_SERVER_URL: http://apm-server:8200
        networks:
            - micros
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == worker]


    user:
        image: registry.local/optimusdeploy_user:dev
        command: npm run dev
        environment:
            NODE_ENV: development
            AMQP_URI: amqp://rabbitmq
            MONGODB_HOST: mongodb://mongodb
            GITHUB_CLIENT_ID: 129800c9747092aabe46
            GITHUB_CLIENT_SECRET: 267225d33106584503b84551d493e77bbdd7b0b8
            GOOGLE_CLIENT_ID: 666163516742-b89cg46pnk6o8p75b9btgp7o03gvv081.apps.googleusercontent.com
            GOOGLE_CLIENT_SECRET: OzxCxTGs8PJedpi4y1VeqdRH
            ELASTIC_APM_SERVICE_NAME: optimus-deploy-user-service
            ELASTIC_APM_SERVER_URL: http://apm-server:8200
        networks:
            - micros
            - db
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == worker]


    container:
        image: registry.local/optimusdeploy_container:dev
        command: npm run dev
        environment:
            NODE_ENV: development
            AMQP_URI: amqp://rabbitmq
            MONGODB_HOST: mongodb://mongodb
            DATA_DIR: /srv/daemon-data
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /srv/daemon-data:/srv/daemon-data
        networks:
            - micros
            - db
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]

            
    mailer:
        image: registry.local/optimusdeploy_mailer:dev
        command: npm run dev
        environment:
            NODE_ENV: development
            AMQP_URI: amqp://rabbitmq
            SENDGRID_API_KEY: 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
        networks:
            - micros
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == worker]
