version: '3.5'

networks:

    elastic:
        name: elastic
        driver: overlay
    proxy:
        name: proxy
        driver: overlay
        external: true
    micros:
        name: micros
        driver: overlay
        external: true

services:

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
        volumes:
            - /srv/elastic/elasticsearch/logs/:/usr/share/elasticsearch/logs/
            - /srv/elastic/elasticsearch/data/:/usr/share/elasticsearch/data
        networks:
            - elastic
        healthcheck:
            test: curl -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
            interval: 30s
            timeout: 10s
            retries: 5
        deploy:
            placement:
                constraints: [node.role == manager]

    kibana:
        image: docker.elastic.co/kibana/kibana:6.6.1
        networks:
            - elastic
            - proxy
        deploy:
            labels:
                - "traefik.docker.network=proxy"
                - "traefik.backend=kibana"
                - "traefik.frontend.rule=Host:kibana.local"
                - "traefik.port=5601"
                - "traefik.enable=true"
            placement:
                constraints: [node.role == manager]
        healthcheck:
            test: curl -s https://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
            interval: 30s
            timeout: 10s
            retries: 5

    metricbeat:
        image: docker.elastic.co/beats/metricbeat:6.6.2
        user: root
        secrets:
            - source: metricbeat.yml
              target: /usr/share/metricbeat/metricbeat.yml
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
            - /proc:/hostfs/proc:ro
            - /:/hostfs:ro
        networks:
            - elastic
        deploy:
            placement:
                constraints: [node.role == manager]    
            restart_policy:
                condition: on-failure
        healthcheck:
            test: metricbeat test config
            interval: 30s
            timeout: 15s
            retries: 5

    filebeat:
        image: docker.elastic.co/beats/filebeat:6.6.2
        user: root
        secrets:
            - source: filebeat.yml
              target: /usr/share/filebeat/filebeat.yml
        volumes:
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - /srv/elastic/filebeat/logs/:/var/log/
            - /var/log/syslog:/var/log/host/syslog
            - /var/log/auth.log:/var/log/host/auth.log
        networks:
            - elastic
        deploy:
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure
        healthcheck:
            test: filebeat test config
            interval: 30s
            timeout: 15s
            retries: 5

    apm-server:
        image: docker.elastic.co/apm/apm-server:6.6.2
        user: root
        networks:
            - elastic
            - micros
        secrets:
            - source: apm-server.yml
              target: /usr/share/apm-server/apm-server.yml
        healthcheck:
            test: apm-server test config
            interval: 30s
            timeout: 15s
            retries: 5
        deploy:
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure

secrets:

    filebeat.yml:
        file: ./config/filebeat/filebeat.yml

    metricbeat.yml:
        file: ./config/metricbeat/metricbeat.yml

    apm-server.yml:
        file: ./config/APM/apm-server.yml