version: '3.5'

networks:

    proxy:
        name: proxy
        driver: overlay
        external: true
    micros:
        name: micros
        driver: overlay
        external: true
    db:
        name: db
        driver: overlay
        external: true

services:

    api:
        image: registry.local/optimusdeploy_api:dev
        command: npm run dev
        environment:
            NODE_ENV: development
            AMQP_URI: amqp://rabbitmq
            API_PORT: 3000
            ELASTIC_APM_SERVICE_NAME: optimus-deploy-api
            ELASTIC_APM_SERVER_URL: http://apm-server:8200
        networks:
            - micros
            - proxy
        deploy:
            replicas: 1
            labels:
                - "traefik.docker.network=proxy"
                - "traefk.docker.domain=api.local"
                - "traefik.backend=api.local"
                - "traefik.frontend.rule=Host:www.api.local,api.local"
                - "traefik.port=3000"
                - "traefik.enable=true"
            placement:
                constraints: [node.role == manager]

    orchestrator:
        image: registry.local/optimusdeploy_orchestrator:dev
        command: npm run dev
        environment:
            NODE_ENV: development
            AMQP_URI: amqp://rabbitmq
        networks:
            - micros
        deploy:
            placement:
                constraints: [node.role == manager]


    user:
        image: registry.local/optimusdeploy_user:dev
        command: npm run dev
        environment:
            NODE_ENV: development
            AMQP_URI: amqp://rabbitmq
            MONGODB_HOST: mongodb://mongodb
        networks:
            - micros
            - db
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]


    container:
        image: registry.local/optimusdeploy_container:dev
        command: npm run dev
        environment:
            NODE_ENV: development
            AMQP_URI: amqp://rabbitmq
            MONGODB_HOST: mongodb://mongodb
        networks:
            - micros
            - db
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]

            
    mailer:
        image: registry.local/optimusdeploy_mailer:dev
        command: npm run dev
        environment:
            NODE_ENV: development
            AMQP_URI: amqp://rabbitmq
            SENDGRID_API_KEY: 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
        networks:
            - micros
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
