version: '3.5'

networks:

    elastic:
        name: elastic
        driver: overlay
        external: true
    micros:
        name: micros
        driver: overlay
        external: true

services:

    metricbeat:
        user: root
        image: docker.elastic.co/beats/metricbeat:6.6.1
        secrets:
            - source: metricbeat.yml
              target: /usr/share/metricbeat/metricbeat.yml
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
            - /proc:/hostfs/proc:ro
            - /:/hostfs:ro
        networks:
            - elastic
        deploy:  
            mode: global
            restart_policy:
                condition: on-failure
        healthcheck:
            test: metricbeat test config
            interval: 30s
            timeout: 15s
            retries: 5

    filebeat:
        user: root
        image: docker.elastic.co/beats/filebeat:6.6.1
        secrets:
            - source: filebeat.yml
              target: /usr/share/filebeat/filebeat.yml
        volumes:
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/log/syslog:/var/log/host/syslog
            - /var/log/auth.log:/var/log/host/auth.log
        networks:
            - elastic
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
        healthcheck:
            test: filebeat test config
            interval: 30s
            timeout: 15s
            retries: 5

    apm-server:
        image: docker.elastic.co/apm/apm-server:6.6.1
        networks:
            - elastic
            - micros
        secrets:
            - source: apm-server.yml
              target: /usr/share/apm-server/apm-server.yml
        healthcheck:
            test: apm-server test config
            interval: 30s
            timeout: 15s
            retries: 5
        deploy:
            mode: global
            restart_policy:
                condition: on-failure

secrets:

    filebeat.yml:
        file: ./config/filebeat/filebeat.yml

    metricbeat.yml:
        file: ./config/metricbeat/metricbeat.yml

    apm-server.yml:
        file: ./config/APM/apm-server.yml