version: '3.6'

networks:

    proxy:
        name: proxy
        driver: overlay
    apps:
        name: apps
        driver: overlay
    micros:
        name: micros
        driver: overlay
    db:
        name: db
        driver: overlay
    bridge:
        name: bridge
        external: true

services:

    mongodb:
        image: mvertes/alpine-mongo
        volumes:
            - /srv/utils/mongodb:/data/db
        networks:
            - db
        deploy:
            placement:
                constraints: [node.role == manager]
    
    rabbitmq:
        image: rabbitmq:3-management
        hostname: rabbitmq
        volumes:
            - /srv/utils/rabbitmq:/var/lib/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=user 
            - RABBITMQ_DEFAULT_PASS=password
        networks:
            - micros
            - proxy
        deploy:
            labels:
                traefik.docker.network: "proxy"
                traefik.backend: "rabbitmq"
                traefik.frontend.rule: "Host:www.rabbitmq.local,rabbitmq.local"
                traefik.port: "15672"
                traefik.enable: "true"
            placement:
                constraints: [node.role == manager]

    registry:
        image: registry:2
        volumes:
            - /srv/utils/registry:/var/lib/registry
        networks:
            - micros
            - proxy
        deploy:
            labels:
                traefik.frontend.rule: "Host:www.registry.local,registry.local"
                traefik.port: "5000"
                traefik.enable: "true"
            placement:
                constraints: [node.role == manager]

    consul-leader:
        image: consul
        command: agent -server -client=0.0.0.0 -bootstrap -ui
        volumes:
            - /srv/utils/consul-leader:/consul/data
        environment:
            - CONSUL_BIND_INTERFACE=eth0
            - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
        networks:
            - proxy
        deploy:
            mode: replicated
            replicas: 1
            labels:
                traefik.backend: "consul"
                traefik.frontend.rule: "Host:www.consul.local,consul.local"
                traefik.port: "8500"
                traefik.enable: "true"
            placement:
                constraints: [node.role == manager]

    consul-replica:
        image: consul
        command: agent -server -client=0.0.0.0 -retry-join="consul-leader"
        volumes:
            - consul-data-replica:/consul/data
        environment:
            - CONSUL_BIND_INTERFACE=eth0
            - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
        networks:
            - proxy
    
    traefik:
        image: traefik
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        configs:
            -   source: traefik_config
                target: /etc/traefik/traefik.toml
            -   source: traefik_crt
                target: /etc/traefik/traefik.crt
            -   source: traefik_key
                target: /etc/traefik/traefik.key
        networks:
            - proxy
            - apps
            - micros
        deploy:
            labels:
                traefik.backend: "traefik"
                traefik.frontend.rule: "Host:www.traefik.local,traefik.local"
                traefik.port: "8080"
                traefik.enable: "true"
            placement:
                constraints: [node.role == manager]
    
    prune:
        image: liske/docker-prune
        command: ["container", "volume"]
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - SLEEP=1800
        networks:
            - bridge


configs:

    traefik_config:
        file: ./config/traefik/traefik-dev.toml
    traefik_crt:
        file: ./config/traefik/traefik.crt
    traefik_key:
        file: ./config/traefik/traefik.key

volumes:
    consul-data-replica: