version: '3.5'

networks:

    elastic:
        name: elastic
        driver: overlay
    proxy:
        name: proxy
        driver: overlay
        external: true

services:

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
        volumes:
            - /srv/elastic/es:/usr/share/elasticsearch/data
        networks:
            - elastic
        healthcheck:
            test: curl -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
            interval: 30s
            timeout: 10s
            retries: 5
        deploy:
            placement:
                constraints: [node.role == manager]

    kibana:
        image: docker.elastic.co/kibana/kibana:6.6.1
        networks:
            - elastic
            - proxy
        deploy:
            labels:
                - "traefik.docker.network=proxy"
                - "traefik.backend=kibana"
                - "traefik.frontend.rule=Host:kibana.local"
                - "traefik.port=5601"
                - "traefik.enable=true"
            placement:
                constraints: [node.role == manager]
        healthcheck:
            test: curl -s https://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
            interval: 30s
            timeout: 10s
            retries: 5