# -*- mode: ruby -*-
# vi: set ft=ruby :

# Variables
SWARM_MANAGERS = 1
SWARM_WORKERS = 2

MEMORY = 1024
CPUS = 1

Vagrant.configure("2") do |config|

    # Spin the managers
    (1..SWARM_MANAGERS).each do |i|
        config.vm.define "manager#{i}" do |manager|
            manager.vm.hostname = "manager#{i}"
            manager.vm.network "private_network", ip: "10.0.10.#{i+1}"
        end
    end

    # Spin the workers
    (1..SWARM_WORKERS).each do |i|
        config.vm.define "worker#{i}" do |worker|
            worker.vm.hostname = "worker#{i}"
            worker.vm.network "private_network", ip: "10.0.20.#{i+1}"
        end
    end

    # Box Settings
    config.vm.box = "ubuntu/bionic64"

    # Provider Settings
    config.vm.provider "virtualbox" do |vb|
        vb.memory = MEMORY
        vb.cpus = CPUS
    end
    
    # Folder Settings
    config.vm.synced_folder "../config", "/root/config"
    
    # Provision Settings
    config.vm.provision "bootstrap", type: "shell", path: "bootstrap.sh"
    config.vm.provision "cert", type: "shell", path: "cert.sh"

end
