debug = true

loglevel = "DEBUG"

defaultEntryPoints = ["http", "https"]

[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
        [[entryPoints.https.tls.certificates]]
        certFile = "/etc/traefik/traefik.crt"
        keyFile = "/etc/traefik/traefik.key"
      
[api]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "traefik.local"
watch = true
exposedbydefault = false
swarmmode = true
network = "proxy"

[accessLog]

[consulCatalog]
endpoint = "consul-leader:8500"