metricbeat.modules: 
  - 
    enabled: true
    hosts: 
      - "unix:///var/run/docker.sock"
    metricsets: 
      - container
      - cpu
      - diskio
      - healthcheck
      - info
      - image
      - memory
      - network
    module: docker
    period: 10s
  - 
    enabled: true
    metricsets: 
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - uptime
    module: system
    period: 10s
    processes: 
      - .*

metricbeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: elasticsearch
          config:
            - module: elasticsearch
              metricsets:
                - node
                - node_stats
                - index
              period: 10s
              hosts: ["${data.host}:9200"]

output.elasticsearch: 
  hosts: 
    - "elasticsearch:9200"

setup.dashboards.enabled: true

setup.kibana: 
  host: "kibana:5601"

setup.template.enabled: true
setup.template.fields: fields.yml
setup.template.name: metricbeat
setup.template.overwrite: false
setup.template.pattern: metricbeat-*
setup.template.settings: 
  _source.enabled: false
