output.elasticsearch:
    hosts: ['elasticsearch:9200']

setup.kibana:
    host: "kibana:5601"

setup.dashboards.enabled: true

metricbeat.modules:
    -   module: docker
        metricsets:
            - "container"
            - "cpu"
            - "diskio"
            - "healthcheck"
            - "info"
            - "image"
            - "memory"
            - "network"
        hosts: ["unix:///var/run/docker.sock"]
        period: 10s
        enabled: true
    -   module: system
        metricsets:
            - cpu             # CPU usage
            - load            # CPU load averages
            - memory          # Memory usage
            - network         # Network IO
            - process         # Per process metrics
            - process_summary # Process summary
            - uptime          # System Uptime
        enabled: true
        period: 10s
        processes: ['.*']